#!/usr/bin/env bash
# Migration 0001 — baseline
#
# This is a no-op. It exists to establish schema version 1 as the baseline that
# shipped with v1.0. Running it confirms the data directory is in the expected
# v1.0 shape; it makes no changes.
#
# Schema at version 1:
#
#   data/openclaw-bridge/bridge-token.txt
#     A hex string generated by setup.sh. No structured schema.
#
#   data/openclaw-bridge/character-links.json
#     JSON object keyed by character name:
#     {
#       "CharacterName": {
#         "oc_agent_id":     string,
#         "active":          boolean,
#         "owner_user_ids":  string[],
#         "send_message_channel": string | undefined,
#         "heartbeat_channel":    string | undefined,
#         "heartbeat": {
#           "enabled":    boolean,
#           "channel_id": string,
#           "target":     string,
#           "interval_ms": number,
#           "idle_ms":     number
#         } | undefined
#       }
#     }
#
# Usage: bash migrations/0001_baseline.sh <data-dir>
set -euo pipefail

data_dir="${1:?Usage: $0 <data-dir>}"

echo "Migration 0001 (baseline): no changes needed."
